package Mantenimiento.Modelo.Pedido;

public enum acciones {
	ALTAPEDIDO,MODIFICARPEDIDO,ELIIMINARPEDIDO,CARGARLISTAPEDIDOS,
	CARGARLISTATAREAS,CARGARPEDIDO,CARGARPEDIDOVISUALIZAR,CARGARPEDIDOMODIFICAR}
