package Mantenimiento.Modelo.Usuarios;

public enum acciones {
	AGREGARUSUARIO,MODIFICARUSUARIO,ELIMINARUSUARIO, CARGARUSUARIO,BUSCARUSUARIO,
		AGREGARROL,MODIFICARROL,ELIMINARROL,CARGARROL,BUSCARROL, 
		AGREGARPERMISO,MODIFICARPERMISO, ELIMINARPERMISO, BUSCARPERMISO, CARGARPERMISO,
		LISTAPERMISOS,COMBOROLES,ERROR,ACCESOVALIDO,ACCESOINVALIDO
}
